"""Menu-bar construction for the main window.

Single responsibility: the entire menu tree lives here; MainWindow only
provides the slots and the small _act/_menu registration helpers.
Extracted verbatim from MainWindow._build_menu_bar.
"""

from PyQt6.QtGui import QAction, QKeySequence, QColor, QPainter, QBrush
from PyQt6.QtCore import Qt, QRectF, QPoint, QPointF
from PyQt6.QtWidgets import QMenu

from core.locale import tr


def build_menu_bar(win) -> None:
    mb = win.menuBar()

    # File
    file_m = win._menu(mb, "menu.file")
    win._act(file_m, "menu.new",        win._new_doc,    QKeySequence.StandardKey.New)
    win._act(file_m, "menu.open",       win._open_file,  QKeySequence.StandardKey.Open)
    
    win._recent_menu = win._menu(file_m, "menu.open_recent")
    win._update_recent_menu()
    
    file_m.addSeparator()
    win._act(file_m, "menu.save",       win._save,       QKeySequence.StandardKey.Save)
    win._act(file_m, "menu.save_as",    win._save_as,    QKeySequence("Ctrl+Shift+S"))
    win._act(file_m, "menu.export_png", win._export_png)
    win._act(file_m, "menu.export_slices", win._export_slices)
    file_m.addSeparator()
    win._act(file_m, "menu.quit",       win.close,       QKeySequence.StandardKey.Quit)

    # Edit
    edit_m = win._menu(mb, "menu.edit")
    win._undo_act = win._act(edit_m, "menu.undo", win._undo, QKeySequence("Ctrl+Z"))
    win._redo_act = win._act(edit_m, "menu.redo", win._redo, QKeySequence("Ctrl+Shift+Z"))
    edit_m.addSeparator()
    win._act(edit_m, "menu.cut",             win._cut,   QKeySequence.StandardKey.Cut)
    win._act(edit_m, "menu.copy",            win._copy,  QKeySequence.StandardKey.Copy)
    win._act(edit_m, "menu.paste_new_layer", win._paste, QKeySequence.StandardKey.Paste)
    edit_m.addSeparator()
    win._act(edit_m, "menu.clear_layer",  win._clear_layer, QKeySequence("Delete"))
    edit_m.addSeparator()
    win._act(edit_m, "menu.define_brush", win._define_brush)
    win._act(edit_m, "menu.define_pattern", win._define_pattern)
    win._act(edit_m, "menu.define_shape", win._define_shape)
    # Select
    select_m = win._menu(mb, "menu.select")
    win._act(select_m, "menu.select_all", win._select_all, QKeySequence.StandardKey.SelectAll) # Ctrl+A
    win._act(select_m, "menu.deselect",   win._deselect,   QKeySequence("Ctrl+D"))
    win._act(select_m, "menu.reselect",   win._reselect,   QKeySequence("Shift+Ctrl+D"))
    win._act(select_m, "menu.inverse",    win._inverse_selection, QKeySequence("Shift+Ctrl+I"))
    select_m.addSeparator()
    win._act(select_m, "menu.color_range", win._color_range)
    win._act(select_m, "menu.focus_area", win._focus_area)
    win._act(select_m, "menu.select_subject", win._select_subject)
    win._act(select_m, "menu.select_sky", win._select_sky)
    win._act(select_m, "menu.select_and_mask", win._select_and_mask, QKeySequence("Alt+Ctrl+R"))
    select_m.addSeparator()
    win._act(select_m, "menu.save_selection", win._save_selection)
    win._act(select_m, "menu.load_selection", win._load_selection)
    select_m.addSeparator()
    
    modify_m = win._menu(select_m, "menu.modify")
    win._act(modify_m, "menu.modify.border", lambda: win._modify_selection("border"))
    win._act(modify_m, "menu.modify.smooth", lambda: win._modify_selection("smooth"))
    win._act(modify_m, "menu.modify.expand", lambda: win._modify_selection("expand"))
    win._act(modify_m, "menu.modify.contract", lambda: win._modify_selection("contract"))
    win._act(modify_m, "menu.modify.feather", lambda: win._modify_selection("feather"), QKeySequence("Shift+F6"))
    win._act(select_m, "menu.quick_mask", win._toggle_quick_mask, QKeySequence("Q"))
    edit_m.addSeparator()
    win._act(edit_m, "menu.fill_fg", win._fill_fg, QKeySequence("Alt+Delete"))
    win._act(edit_m, "menu.fill_bg", win._fill_bg, QKeySequence("Ctrl+Delete"))

    # Image
    img_m  = win._menu(mb, "menu.image")
    adj_m  = win._menu(img_m, "menu.adjustments")
    win._act(adj_m, "menu.levels",              win._levels,              QKeySequence("Ctrl+L"))
    win._act(adj_m, "menu.curves",               win._curves,             QKeySequence("Ctrl+M"))
    win._act(adj_m, "menu.brightness_contrast", win._brightness_contrast)
    win._act(adj_m, "menu.hue_saturation",      win._hue_saturation)
    win._act(adj_m, "menu.exposure",            win._exposure)
    win._act(adj_m, "menu.vibrance",            win._vibrance)
    adj_m.addSeparator()
    win._act(adj_m, "menu.black_white",         win._black_white)
    win._act(adj_m, "menu.posterize",           win._posterize)
    win._act(adj_m, "menu.threshold",           win._threshold)
    adj_m.addSeparator()
    win._act(adj_m, "menu.channel_mixer",       win._channel_mixer)
    win._act(adj_m, "menu.selective_color",     win._selective_color)
    win._act(adj_m, "menu.match_color",         win._match_color)
    adj_m.addSeparator()
    win._act(adj_m, "menu.shadows_highlights",  win._shadows_highlights)
    win._act(adj_m, "menu.replace_color",       win._replace_color)
    adj_m.addSeparator()
    win._act(adj_m, "menu.photo_filter",        win._photo_filter)
    win._act(adj_m, "menu.gradient_map",        win._gradient_map)
    win._act(adj_m, "menu.color_lookup",        win._color_lookup)
    win._act(adj_m, "menu.equalize",            win._equalize)
    adj_m.addSeparator()
    win._act(adj_m, "menu.hdr_toning",          win._hdr_toning)
    adj_m.addSeparator()
    win._act(adj_m, "menu.invert",              win._invert, QKeySequence("Ctrl+I"))
    img_m.addSeparator()
    win._act(img_m, "menu.flip_h",        win._flip_h)
    win._act(img_m, "menu.flip_v",        win._flip_v)
    img_m.addSeparator()
    mode_m = win._menu(img_m, "menu.mode")
    win._act_mode_bitmap = win._act(mode_m, "mode.bitmap", lambda: win._change_color_mode("Bitmap"))
    win._act_mode_gray = win._act(mode_m, "mode.grayscale", lambda: win._change_color_mode("Grayscale"))
    win._act_mode_duo = win._act(mode_m, "mode.duotone", lambda: win._change_color_mode("Duotone"))
    win._act_mode_idx = win._act(mode_m, "mode.indexed", lambda: win._change_color_mode("Indexed"))
    win._act_mode_rgb = win._act(mode_m, "mode.rgb", lambda: win._change_color_mode("RGB"))
    win._act_mode_cmyk = win._act(mode_m, "mode.cmyk", lambda: win._change_color_mode("CMYK"))
    win._act_mode_lab = win._act(mode_m, "mode.lab", lambda: win._change_color_mode("Lab"))
    
    mode_m.addSeparator()
    win._act_depth_8 = win._act(mode_m, "mode.8bit", lambda: win._change_bit_depth(8))
    win._act_depth_16 = win._act(mode_m, "mode.16bit", lambda: win._change_bit_depth(16))
    win._act_depth_32 = win._act(mode_m, "mode.32bit", lambda: win._change_bit_depth(32))
    
    for act in (win._act_mode_bitmap, win._act_mode_gray, win._act_mode_duo, win._act_mode_idx, win._act_mode_rgb, win._act_mode_cmyk, win._act_mode_lab, 
                win._act_depth_8, win._act_depth_16, win._act_depth_32):
        act.setCheckable(True)
    img_m.addSeparator()
    win._act(img_m, "menu.apply_image",   win._apply_image)
    win._act(img_m, "menu.calculations",  win._calculations)
    img_m.addSeparator()
    win._act(img_m, "menu.image_size",    win._image_size,    QKeySequence("Ctrl+Alt+I"))
    win._act(img_m, "menu.resize_canvas", win._resize_canvas)
    img_m.addSeparator()
    win._act(img_m, "menu.trim",       win._trim)
    win._act(img_m, "menu.reveal_all", win._reveal_all)
    img_m.addSeparator()
    win._act(img_m, "menu.apply_crop",    win._apply_crop)
    win._act(img_m, "menu.apply_perspective_crop", win._apply_perspective_crop)
    img_m.addSeparator()
    win._act(img_m, "menu.flatten",       win._flatten)

    # Layer
    layer_m = win._menu(mb, "menu.layer")
    win._act(layer_m, "menu.new_layer",       win._add_layer,       QKeySequence("Ctrl+Shift+N"))
    win._act(layer_m, "menu.duplicate_layer", win._duplicate_layer, QKeySequence("Ctrl+J"))
    win._act(layer_m, "menu.delete_layer",    win._delete_layer)
    layer_m.addSeparator()
    win._act(layer_m, "menu.export_layer_png", win._export_layer_png)
    layer_m.addSeparator()
    win._act(layer_m, "menu.create_clipping", win._toggle_clipping_mask, QKeySequence("Ctrl+Alt+G"))

    adj_m = win._menu(layer_m, "menu.new_adj_layer")
    win._act(adj_m, "menu.new_adj_bc",     lambda: win._new_adj_layer("brightness_contrast"))
    win._act(adj_m, "menu.new_adj_hs",     lambda: win._new_adj_layer("hue_saturation"))
    win._act(adj_m, "menu.new_adj_invert", lambda: win._new_adj_layer("invert"))
    adj_m.addSeparator()
    win._act(adj_m, "menu.levels",       lambda: win._new_adj_layer("levels"))
    win._act(adj_m, "menu.curves",       lambda: win._new_adj_layer("curves"))
    win._act(adj_m, "menu.exposure",     lambda: win._new_adj_layer("exposure"))
    win._act(adj_m, "menu.vibrance",     lambda: win._new_adj_layer("vibrance"))
    win._act(adj_m, "menu.black_white",  lambda: win._new_adj_layer("black_white"))
    win._act(adj_m, "menu.posterize",    lambda: win._new_adj_layer("posterize"))
    win._act(adj_m, "menu.threshold",    lambda: win._new_adj_layer("threshold"))
    win._act(adj_m, "menu.photo_filter", lambda: win._new_adj_layer("photo_filter"))
    win._act(adj_m, "menu.gradient_map", lambda: win._new_adj_layer("gradient_map"))
    win._act(adj_m, "menu.color_lookup", lambda: win._new_adj_layer("color_lookup"))

    fill_m = win._menu(layer_m, "menu.new_fill_layer")
    win._act(fill_m, "menu.new_fill_solid",    lambda: win._new_fill_layer("solid"))
    win._act(fill_m, "menu.new_fill_gradient", lambda: win._new_fill_layer("gradient"))

    layer_m.addSeparator()
    win._act(layer_m, "menu.smart_object",   win._new_smart_object)
    win._act(layer_m, "menu.rasterize_layer", win._rasterize_layer)
    layer_m.addSeparator()
    win._act(layer_m, "menu.move_up",   win._layer_up,   QKeySequence("Ctrl+]"))
    win._act(layer_m, "menu.move_down", win._layer_down, QKeySequence("Ctrl+["))

    # Filter
    filter_m = win._menu(mb, "menu.filter")
    
    win._act(filter_m, "menu.filter.camera_raw",      lambda: win._open_specific_filter("camera_raw"), QKeySequence("Shift+Ctrl+A"))
    win._act(filter_m, "menu.filter.lens_correction", lambda: win._open_specific_filter("lens_correction"), QKeySequence("Shift+Ctrl+R"))
    win._act(filter_m, "menu.filter.liquify",         lambda: win._open_specific_filter("liquify"), QKeySequence("Shift+Ctrl+X"))
    filter_m.addSeparator()
    
    blur_gallery_m = win._menu(filter_m, "menu.blur_gallery")
    win._act(blur_gallery_m, "menu.blur.field",      win._blur_field)
    win._act(blur_gallery_m, "menu.blur.iris",       win._blur_iris)
    win._act(blur_gallery_m, "menu.blur.tilt_shift", win._blur_tilt_shift)
    win._act(blur_gallery_m, "menu.blur.path",       win._blur_path)
    win._act(blur_gallery_m, "menu.blur.spin",       win._blur_spin)
    filter_m.addSeparator()

    blur_m   = win._menu(filter_m, "menu.blur")
    win._act(blur_m, "menu.blur.average",  win._blur_average)
    win._act(blur_m, "menu.blur.blur",     win._blur_simple)
    win._act(blur_m, "menu.blur.more",     win._blur_more)
    blur_m.addSeparator()
    win._act(blur_m, "menu.blur.box",      win._box_blur)
    win._act(blur_m, "menu.blur.gaussian", win._gaussian_blur)
    win._act(blur_m, "menu.blur.motion",   win._motion_blur)
    win._act(blur_m, "menu.blur.radial",   win._radial_blur)
    win._act(blur_m, "menu.blur.smart",    win._smart_blur)
    win._act(blur_m, "menu.blur.surface",  win._surface_blur)
    win._act(blur_m, "menu.blur.shape",    win._shape_blur)
    win._act(blur_m, "menu.blur.lens",     win._lens_blur)
    filter_m.addSeparator()
    
    sharpen_m = win._menu(filter_m, "menu.sharpen_gallery")
    win._act(sharpen_m, "menu.sharpen.sharpen", lambda: win._open_sharpen("sharpen"))
    win._act(sharpen_m, "menu.sharpen.edges",   lambda: win._open_sharpen("edges"))
    win._act(sharpen_m, "menu.sharpen.more",    lambda: win._open_sharpen("more"))
    win._act(sharpen_m, "menu.sharpen.smart",   lambda: win._open_sharpen("smart"))
    win._act(sharpen_m, "menu.sharpen.unsharp", lambda: win._open_sharpen("unsharp"))
    filter_m.addSeparator()

    distort_m = win._menu(filter_m, "menu.distort")
    win._act(distort_m, "menu.distort.displace", lambda: win._open_distort("displace"))
    win._act(distort_m, "menu.distort.pinch",    lambda: win._open_distort("pinch"))
    win._act(distort_m, "menu.distort.polar",    lambda: win._open_distort("polar"))
    win._act(distort_m, "menu.distort.ripple",   lambda: win._open_distort("ripple"))
    win._act(distort_m, "menu.distort.shear",    lambda: win._open_distort("shear"))
    win._act(distort_m, "menu.distort.spherize", lambda: win._open_distort("spherize"))
    win._act(distort_m, "menu.distort.twirl",    lambda: win._open_distort("twirl"))
    win._act(distort_m, "menu.distort.wave",     lambda: win._open_distort("wave"))
    win._act(distort_m, "menu.distort.zigzag",   lambda: win._open_distort("zigzag"))
    
    filter_m.addSeparator()
    noise_m = win._menu(filter_m, "menu.noise")
    win._act(noise_m, "menu.noise.add",      lambda: win._open_noise("add_noise"))
    win._act(noise_m, "menu.noise.despeckle",lambda: win._open_noise("despeckle"))
    win._act(noise_m, "menu.noise.dust",     lambda: win._open_noise("dust_scratches"))
    win._act(noise_m, "menu.noise.median",   lambda: win._open_noise("median"))
    win._act(noise_m, "menu.noise.reduce",   lambda: win._open_noise("reduce_noise"))
    
    filter_m.addSeparator()
    pixelate_m = win._menu(filter_m, "menu.pixelate")
    win._act(pixelate_m, "menu.pixelate.color_halftone", lambda: win._open_pixelate("color_halftone"))
    win._act(pixelate_m, "menu.pixelate.crystallize",    lambda: win._open_pixelate("crystallize"))
    win._act(pixelate_m, "menu.pixelate.facet",          lambda: win._open_pixelate("facet"))
    win._act(pixelate_m, "menu.pixelate.fragment",       lambda: win._open_pixelate("fragment"))
    win._act(pixelate_m, "menu.pixelate.mezzotint",      lambda: win._open_pixelate("mezzotint"))
    win._act(pixelate_m, "menu.pixelate.mosaic",         lambda: win._open_pixelate("mosaic"))
    win._act(pixelate_m, "menu.pixelate.pointillize",    lambda: win._open_pixelate("pointillize"))
    
    filter_m.addSeparator()
    other_m = win._menu(filter_m, "menu.other")
    win._act(other_m, "menu.other.custom",    lambda: win._open_other("custom"))
    win._act(other_m, "menu.other.high_pass", lambda: win._open_other("high_pass"))
    win._act(other_m, "menu.other.maximum",   lambda: win._open_other("maximum"))
    win._act(other_m, "menu.other.minimum",   lambda: win._open_other("minimum"))
    win._act(other_m, "menu.other.offset",    lambda: win._open_other("offset"))
    
    filter_m.addSeparator()
    stylize_m = win._menu(filter_m, "menu.stylize")
    win._act(stylize_m, "menu.stylize.emboss",       lambda: win._open_stylize("emboss"))
    win._act(stylize_m, "menu.stylize.extrude",      lambda: win._open_stylize("extrude"))
    win._act(stylize_m, "menu.stylize.find_edges",   lambda: win._open_stylize("find_edges"))
    win._act(stylize_m, "menu.stylize.oil_paint",    lambda: win._open_stylize("oil_paint"))
    win._act(stylize_m, "menu.stylize.solarize",     lambda: win._open_stylize("solarize"))
    win._act(stylize_m, "menu.stylize.tiles",        lambda: win._open_stylize("tiles"))
    win._act(stylize_m, "menu.stylize.trace_contour",lambda: win._open_stylize("trace_contour"))
    win._act(stylize_m, "menu.stylize.wind",         lambda: win._open_stylize("wind"))
    
    filter_m.addSeparator()
    render_m = win._menu(filter_m, "menu.render_gallery")
    win._act(render_m, "menu.render.clouds",      lambda: win._open_render("clouds"))
    win._act(render_m, "menu.render.diff_clouds", lambda: win._open_render("diff_clouds"))
    win._act(render_m, "menu.render.fibers",      lambda: win._open_render("fibers"))
    win._act(render_m, "menu.render.lens_flare",  lambda: win._open_render("lens_flare"))
    win._act(render_m, "menu.render.lighting",    lambda: win._open_render("lighting"))
    win._act(render_m, "menu.render.wood",        lambda: win._open_render("wood"))
    win._act(render_m, "menu.render.frame",       lambda: win._open_render("frame"))
    win._act(render_m, "menu.render.flame",       lambda: win._open_render("flame"))

    # View
    view_m = win._menu(mb, "menu.view")
    win._act(view_m, "menu.zoom_in",    lambda: win._canvas and win._canvas.zoom_in(),    QKeySequence.StandardKey.ZoomIn)
    win._act(view_m, "menu.zoom_out",   lambda: win._canvas and win._canvas.zoom_out(),   QKeySequence.StandardKey.ZoomOut)
    win._act(view_m, "menu.fit_window", lambda: win._canvas and win._canvas.reset_zoom(), QKeySequence("Ctrl+0"))
    view_m.addSeparator()

    win._act_rulers = win._act(view_m, "menu.rulers", win._toggle_rulers, QKeySequence("Ctrl+R"))
    win._act_rulers.setCheckable(True)
    win._act_rulers.setChecked(False)

    show_m = win._menu(view_m, "menu.show")
    win._act_guides = win._act(show_m, "menu.show_guides", win._toggle_guides, QKeySequence("Ctrl+;"))
    win._act_guides.setCheckable(True); win._act_guides.setChecked(True)
    
    win._act_grid = win._act(show_m, "menu.show_grid", win._toggle_grid, QKeySequence("Ctrl+'"))
    win._act_grid.setCheckable(True); win._act_grid.setChecked(False)
    
    win._act_slices = win._act(show_m, "menu.show_slices", win._toggle_slices)
    win._act_slices.setCheckable(True); win._act_slices.setChecked(True)

    snap_m = win._menu(view_m, "menu.snap")
    win._act_snap = win._act(snap_m, "menu.snap", win._toggle_snap, QKeySequence("Shift+Ctrl+;"))
    win._act_snap.setCheckable(True); win._act_snap.setChecked(True)

    snap_m.addSeparator()
    win._act_snap_guides = win._act(snap_m, "menu.snap_guides", win._toggle_snap_guides)
    win._act_snap_guides.setCheckable(True); win._act_snap_guides.setChecked(True)
    win._act_snap_grid = win._act(snap_m, "menu.snap_grid", win._toggle_snap_grid)
    win._act_snap_grid.setCheckable(True); win._act_snap_grid.setChecked(False)
    win._act_snap_bounds = win._act(snap_m, "menu.snap_bounds", win._toggle_snap_bounds)
    win._act_snap_bounds.setCheckable(True); win._act_snap_bounds.setChecked(True)
    win._act_snap_layers = win._act(snap_m, "menu.snap_layers", win._toggle_snap_layers)
    win._act_snap_layers.setCheckable(True); win._act_snap_layers.setChecked(True)

    view_m.addSeparator()
    win._act(view_m, "menu.clear_guides", win._clear_guides)
    view_m.addSeparator()
    win._build_theme_menu(view_m)
    win._build_language_menu(view_m)

    # Window — dock panel visibility (actions come from the docks
    # themselves, so check state and title always match reality)
    win_m = win._menu(mb, "menu.window")
    for key, act in win._panel_manager.toggle_actions():
        win_m.addAction(act)
    win_m.addSeparator()
    win._act(win_m, "menu.reset_workspace", win._reset_workspace)
